using Microsoft.Data.SqlClient;
using StudentCrudApp.Models;

namespace StudentCrudApp.Data
{
    // This is the ADO.NET "raw" data access layer.

    public class StudentRepository
    {
        private readonly DatabaseHelper _dbHelper;

        public StudentRepository(DatabaseHelper dbHelper)
        {
            _dbHelper = dbHelper;
        }

        // ---------- CREATE ----------
        public int Add(Student student)
        {
            const string sql = @"
                INSERT INTO Students (FullName, Course, Gpa)
                VALUES (@FullName, @Course, @Gpa);
                SELECT CAST(SCOPE_IDENTITY() AS INT);";

            using SqlConnection connection = _dbHelper.GetConnection();
            using SqlCommand command = new SqlCommand(sql, connection);

            command.Parameters.AddWithValue("@FullName", student.FullName);
            command.Parameters.AddWithValue("@Course", student.Course);
            command.Parameters.AddWithValue("@Gpa", student.Gpa);

            // ExecuteScalar returns the single value the query produces —
            // here, the new Id generated by SCOPE_IDENTITY().
            object? result = command.ExecuteScalar();
            return Convert.ToInt32(result);
        }

        // ---------- READ (all) ----------
        public List<Student> GetAll()
        {
            const string sql = "SELECT Id, FullName, Course, Gpa FROM Students ORDER BY Id;";

            var students = new List<Student>();

            using SqlConnection connection = _dbHelper.GetConnection();
            using SqlCommand command = new SqlCommand(sql, connection);
            using SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                students.Add(MapReaderToStudent(reader));
            }

            return students;
        }

        // ---------- READ (by id) ----------
        public Student? GetById(int id)
        {
            const string sql = "SELECT Id, FullName, Course, Gpa FROM Students WHERE Id = @Id;";

            using SqlConnection connection = _dbHelper.GetConnection();
            using SqlCommand command = new SqlCommand(sql, connection);
            command.Parameters.AddWithValue("@Id", id);

            using SqlDataReader reader = command.ExecuteReader();

            if (reader.Read())
            {
                return MapReaderToStudent(reader);
            }

            return null; // not found
        }

        // ---------- UPDATE ----------
        public bool Update(Student student)
        {
            const string sql = @"
                UPDATE Students
                SET FullName = @FullName,
                    Course = @Course,
                    Gpa = @Gpa
                WHERE Id = @Id;";

            using SqlConnection connection = _dbHelper.GetConnection();
            using SqlCommand command = new SqlCommand(sql, connection);

            command.Parameters.AddWithValue("@FullName", student.FullName);
            command.Parameters.AddWithValue("@Course", student.Course);
            command.Parameters.AddWithValue("@Gpa", student.Gpa);
            command.Parameters.AddWithValue("@Id", student.Id);

            int rowsAffected = command.ExecuteNonQuery();
            return rowsAffected > 0; // tells the caller whether a row actually matched
        }

        // ---------- DELETE ----------
        public bool Delete(int id)
        {
            const string sql = "DELETE FROM Students WHERE Id = @Id;";

            using SqlConnection connection = _dbHelper.GetConnection();
            using SqlCommand command = new SqlCommand(sql, connection);
            command.Parameters.AddWithValue("@Id", id);

            int rowsAffected = command.ExecuteNonQuery();
            return rowsAffected > 0;
        }

        // Small helper so we don't repeat the same column-reading code
        // in GetAll() and GetById().
        private static Student MapReaderToStudent(SqlDataReader reader)
        {
            return new Student
            {
                Id = reader.GetInt32(reader.GetOrdinal("Id")),
                FullName = reader.GetString(reader.GetOrdinal("FullName")),
                Course = reader.GetString(reader.GetOrdinal("Course")),
                Gpa = reader.GetDouble(reader.GetOrdinal("Gpa"))
            };
        }
    }
}
